config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'welcome#index'
  resources :time_entries, only: [:index, :create]
  resources :reports, only: :index do
    get :time_entries, on: :collection
  end
end

app/models/time_entry.rb
class TimeEntry
  include Mongoid::Document
  include Mongoid::Timestamps

  field :date, type: Date
  field :time, type: Float
  field :distance, type: Float
  field :avg_speed, type: Float
  belongs_to :user

  validates :date, presence: true
  validates :distance, presence: true, numericality: {
    greater_than: 0
  }
  validates :time, presence: true, numericality: {
    greater_than: 0
  }

  after_validation :calculate_avg_speed

  private

  def calculate_avg_speed
    self.avg_speed = distance.to_f/time
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  field :first_name, type: String
  field :last_name, type: String
  include Mongoid::Timestamps

  has_many :time_entries

  class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]['$oid'])
      record if record && record.authenticatable_salt == salt
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  after_filter :set_csrf_cookie_for_ng

  layout :layout

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def layout
    return false if controller_name != 'welcome'
    'application'
  end

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def time_entries
    render json: TimeEntriesSearch.new(current_user, search_params).totals
  end

  private

  def search_params
    params.permit(:from, :to)
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_filter :authenticate_user!

  expose(:time_entries, ancestor: :current_user)
  expose(:time_entry, attributes: :time_entry_params)

  respond_to :html, :json

  def index
    respond_to do |format|
      format.json{
        self.time_entries = TimeEntriesSearch.new(current_user, search_params).results
        render json: time_entries
      }
      format.html
    end
  end

  def show
  end

  def create
    time_entry.save
    respond_with time_entry, location: nil
  end

  private

  def time_entry_params
    unless params[:time_entry][:date].present?
      params[:time_entry][:date] = Date.today
    end
    params.require(:time_entry).permit(
      :date, :time, :distance
    )
  end

  def search_params
    params.permit(:from, :to)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :html, :json
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :html, :json
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{:role => "navigation"}(ng-controller='HeaderController' ng-show='isUserLoggedIn()')
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#main-header", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} JogNow
    #main-header.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li(ng-class='{ active: isActive("/timesheet") }')
          %a{:href => "#/timesheet"} Timesheet
        %li(ng-class='{ active: isActive("/reports") }')
          %a{:href => "#/reports"} Reports
        %li
          %a(ng-click='signOut()' href='') Logout
      %ul.nav.navbar-nav.navbar-right
        %li
          %a(href='') Welcome, {{ username() }}

app/views/layouts/application.html.haml
%html
  %head
    %title JogNow
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body(ng-app='Jognow')
    = render 'layouts/header'
    .container
      %div(ng-view)

app/views/reports/index.html.haml
%div(ng-controller='ReportsController')
  .row
    .col-lg-12
      .btn-group.pull-left
        %button.btn.btn-default(type='button' ng-click='goToLastWeek()')
          %span.glyphicon.glyphicon-chevron-left
        %button.btn.btn-default(type='button' ng-click='goToNextWeek()')
          %span.glyphicon.glyphicon-chevron-right
      .lead.col-lg-10
        Week:
        %small(ng-cloak) {{ search.from | date:'dd MMM yyyy' }} - {{ search.to | date:'dd MMM yyyy' }}
  .row
    .col-lg-12
      %table.table.table-striped
        %thead
          %tr
            %th Distance
            %th Average Speed (m/s)
            %th Average Speed (km/h)
        %tbody
          %tr
            %td(ng-bind='report.distance | distance')
            %td(ng-bind='report.avg_speed | number:2')
            %td(ng-bind='report.avg_speed | speedToKmH | number:2')

app/views/time_entries/index.html.haml
%div(ng-controller='TimeEntriesController')
  .row
    %form.col-lg-12(ng-submit='create()' name='form' novalidate)
      .row
        .form-group.col-lg-2(ng-class="{ 'has-error': form.date.$invalid && submitted }")
          %label Date
          %input.form-control#date(type='text'
            ng-model='timeEntry.date'
            name='date'
            required bs-datepicker
            data-date-format='dd/MM/yyyy'
            data-max-date='today'
          )
          %span.help-block(ng-show='form.date.$invalid')
            Date is invalid. Valid format: dd/mm/yyyy
        .form-group.col-lg-2(ng-class="{ 'has-error': form.distance.$invalid && submitted }")
          %label Distance
          %input.form-control(type='text' placeholder='3.5km, 400m, etc.' ng-model='timeEntry.distance' name='distance' distance required)
          %span.help-block(ng-show='form.distance.$error.required && submitted')
            Please fill out this field
          %span.help-block(ng-show='form.distance.$error.distance && submitted')
            Distance is not valid. Valid inputs: 3.5km, 400m, 120m
        .form-group.col-lg-2(ng-class="{ 'has-error': form.time.$invalid && submitted }")
          %label Time
          %input.form-control(type='text' placeholder='20 min, 3 hrs, 1 hr' ng-model='timeEntry.time' name='time' required time)
          %span.help-block(ng-show='form.time.$error.required && submitted')
            Please fill out this field
          %span.help-block(ng-show='form.time.$error.time && submitted')
            Time is not valid. Valid inputs: 3 hrs, 3 h, 20 minutes, 10 min
      .row
        .form-group.col-lg-6
          %input.btn.btn-primary(type='submit' value='Save')
  .row
    .col-lg-12
      %form.form-inline(ng-submit='query()' name='searchForm' novalidate)
        .form-group(ng-class="{ 'has-error': searchForm.from.$invalid }")
          %label.control-label Filter
          %input.form-control( type='text'
            ng-model='search.from'
            name='from'
            placeholder='From'
            bs-datepicker
            data-date-format='dd/MM/yyyy'
            data-max-date='{{ search.to }}'
          )
        .form-group(ng-class="{ 'has-error': searchForm.to.$invalid }")
          %input.form-control(type='text'
            ng-model='search.to'
            name='to'
            placeholder='To'
            bs-datepicker
            data-date-format='dd/MM/yyyy'
            data-min-date='{{ search.from }}'
          )
  .row
    .col-lg-12
      %table.table.table-striped
        %thead
          %tr
            %th Date
            %th Distance
            %th Time
            %th Average Speed (m/s)
            %th Average Speed (km/h)
        %tbody
          %tr(ng-repeat='timeEntry in timeEntries')
            %td(ng-bind='timeEntry.date | date:\'dd/MM/yyyy\'')
            %td(ng-bind='timeEntry.distance | distance')
            %td(ng-bind='timeEntry.time | time')
            %td(ng-bind='timeEntry.avg_speed | number:2')
            %td(ng-bind='timeEntry.avg_speed | speedToKmH | number:2')

app/views/time_entries/show.html.haml
%div(ng-controller='TimeEntriesController')
  .row
    %form.col-lg-12(ng-submit='create()' name='form' novalidate)
      .row
        .form-group.col-lg-2(ng-class="{ 'has-error': form.date.$invalid && submitted }")
          %label Date
          %input.form-control(type='text' ng-model='timeEntry.date' name='date' required bs-datepicker)
          %span.help-block(ng-show='form.date.$error.required && submitted')
            Please fill out this field
        .form-group.col-lg-2(ng-class="{ 'has-error': form.distance.$invalid && submitted }")
          %label Distance
          %input.form-control(type='text' placeholder='3.5km, 400m, etc.' ng-model='timeEntry.distance' name='distance' distance required)
          %span.help-block(ng-show='form.distance.$error.required && submitted')
            Please fill out this field
          %span.help-block(ng-show='form.distance.$error.distance && submitted')
            This is not a valid distance. It should contain a valid number followed by a valid measure unit: km for kilometers or m for meters: 3km, 3.5km, 400m, 120m
        .form-group.col-lg-2(ng-class="{ 'has-error': form.time.$invalid && submitted }")
          %label Time
          %input.form-control(type='text' placeholder='20 min, 3 hrs, 1 hr' ng-model='timeEntry.time' name='time' required time)
          %span.help-block(ng-show='form.time.$error.required && submitted')
            Please fill out this field
          %span.help-block(ng-show='form.time.$error.time && submitted')
            This is not a valid time. It should contain a valid number followed by a valid time unit: hrs, hours, m, minutes
      .row
        .form-group.col-lg-6
          %input.btn.btn-primary(type='submit' value='Save')
  %ul.row
    %li.col-lg-12
      .row
        .col-lg-2
          %strong Date
        .col-lg-2
          %strong Distance
        .col-lg-2
          %strong Time
        .col-lg-2
          %strong Average Speed
    %li.col-lg-12(ng-repeat='timeEntry in timeEntries')
      .row
        .col-lg-2(ng-bind='timeEntry.date')
        .col-lg-2(ng-bind='timeEntry.distance')
        .col-lg-2(ng-bind='timeEntry.time')
        .col-lg-2(ng-bind='timeEntry.avg_speed')

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>